// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import common "github.com/Amari-Mecheri/GoSnakeLogic/pkg/common"
import mock "github.com/stretchr/testify/mock"

// Candyer is an autogenerated mock type for the Candyer type
type Candyer struct {
	mock.Mock
}

// Alive provides a mock function with given fields:
func (_m *Candyer) Alive() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Init provides a mock function with given fields: newPosition
func (_m *Candyer) Init(newPosition common.Position) {
	_m.Called(newPosition)
}

// Position provides a mock function with given fields:
func (_m *Candyer) Position() common.Position {
	ret := _m.Called()

	var r0 common.Position
	if rf, ok := ret.Get(0).(func() common.Position); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(common.Position)
	}

	return r0
}

// Remove provides a mock function with given fields:
func (_m *Candyer) Remove() {
	_m.Called()
}
